/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Data.DatabaseAcc;
import Model.Grade;
import Model.SinhVien;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class QLDiem extends javax.swing.JFrame {

    /**
     * Creates new form QLDiem
     */
     Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Grade grade;
    int pos = 0;
    public QLDiem() {
        initComponents();
        txtHoTenSV.setEditable(false);
        txtMaSV.setEditable(false);
         txtDiemTB.setEditable(false);
         showTable();
    }
public ResultSet find(String s){
    try {
             // TODO add your handling code here:
             con = DatabaseAcc.getDatabaseAcc();
             pst = con.prepareStatement("SELECT * FROM SinhVien WHERE MaSV = ?");
             pst.setString(1, s);
            rs = pst.executeQuery();
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex.getMessage());
         }
    return rs;
}
 public boolean CheckInput(){
        if(txtMaSV.getText()==null || txtHoTenSV.getText()==null){
            return false;
        }else{
            try{
                Double.parseDouble(txtTiengAnh.getText());
                Double.parseDouble(txtTinHoc.getText());
                Double.parseDouble(txtGiaoDucTC.getText());
                Double.parseDouble(txtDiemTB.getText());
                return true;
            }catch(Exception E){
                return false;
            }
        }
    }
     public ArrayList<Grade> getGradeList(){
         ArrayList<Grade> grades = new ArrayList<Grade>();
            con = DatabaseAcc.getDatabaseAcc();
            String query = "SELECT * FROM grade ORDER BY DiemTB DESC LIMIT 3";
        try {
            st = con.createStatement();
            rs = st.executeQuery(query);
            while(rs.next()){
                grade = new Grade(rs.getInt("id"), rs.getString("MaSV"), rs.getString("HoTenSV"),
                        Double.parseDouble(rs.getString("TiengAnh")),Double.parseDouble(rs.getString("TinHoc")),
                        Double.parseDouble(rs.getString("GDTC")),Double.parseDouble(rs.getString("DiemTB")));
                grades.add(grade);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLSV.class.getName()).log(Level.SEVERE, null, ex);
        }
      return grades;
    }
      public void showTable(){
        ArrayList<Grade> list = getGradeList();
        DefaultTableModel model = (DefaultTableModel) tbhienthi.getModel();
        //clead khi chạy không chồng dữ liệu lên nhau
        model.setRowCount(0);
        Object[] row = new Object[6];
        for(int i =0;i<list.size();i++){
            row[0] = list.get(i).getMaSV();
            row[1] = list.get(i).getHoTenSV();
            row[2] = list.get(i).getTiengAnh();
            row[3] = list.get(i).getTinHoc();
            row[4] = list.get(i).getGDTC();
            row[5] = list.get(i).getDiemTB();
            model.addRow(row);
        }
    }
      public void ShowItem(int index){
        txtMaSV.setText(getGradeList().get(index).getMaSV());
        txtHoTenSV.setText(getGradeList().get(index).getHoTenSV());
         txtTiengAnh.setText(Double.toString(getGradeList().get(index).getTiengAnh()));
          txtTinHoc.setText(Double.toString(getGradeList().get(index).getTinHoc()));
          txtGiaoDucTC.setText(Double.toString(getGradeList().get(index).getGDTC()));
          txtDiemTB.setText(Double.toString(getGradeList().get(index).getDiemTB()));
    }
      public void Clead(){
          txtMaSV.setText("");
          txtHoTenSV.setText("");
          txtTiengAnh.setText("");
          txtTinHoc.setText("");
          txtGiaoDucTC.setText("");
          txtDiemTB.setText("");
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTiemKiemMaSV = new javax.swing.JTextField();
        bntsearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTenSV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTiengAnh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTinHoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGiaoDucTC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDiemTB = new javax.swing.JTextField();
        bntNew = new javax.swing.JButton();
        bntSave = new javax.swing.JButton();
        bntdelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bntfirst = new javax.swing.JButton();
        bntnext = new javax.swing.JButton();
        bntprevious = new javax.swing.JButton();
        bntlast = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbhienthi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Điểm");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Quản Lý Điểm Sinh Viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tìm Kiếm");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mã SV:");

        bntsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_search.png"))); // NOI18N
        bntsearch.setText("Search");
        bntsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtTiemKiemMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTiemKiemMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Họ Tên SV:");

        txtHoTenSV.setForeground(new java.awt.Color(51, 0, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mã SV:");

        txtMaSV.setForeground(new java.awt.Color(51, 0, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tiếng Anh:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tin Học:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Giáo dục TC:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Điểm TB:");

        txtDiemTB.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDiemTB.setForeground(new java.awt.Color(51, 0, 255));
        txtDiemTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiemTBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTinHoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txtTiengAnh, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoTenSV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiaoDucTC))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtDiemTB)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHoTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGiaoDucTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bntNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_add.png"))); // NOI18N
        bntNew.setText("New");
        bntNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNewActionPerformed(evt);
            }
        });

        bntSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_save.png"))); // NOI18N
        bntSave.setText("Save");
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });

        bntdelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_delete.png"))); // NOI18N
        bntdelete.setText("Delete");
        bntdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdeleteActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bntfirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon10.png"))); // NOI18N
        bntfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntfirstActionPerformed(evt);
            }
        });

        bntnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon7.png"))); // NOI18N
        bntnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntnextActionPerformed(evt);
            }
        });

        bntprevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon8.png"))); // NOI18N
        bntprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntpreviousActionPerformed(evt);
            }
        });

        bntlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon9.png"))); // NOI18N
        bntlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntlastActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("3 Sinh Viên Có Điểm Cao Nhất:");

        tbhienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ Tên", "Tiếng Anh", "Tin Học", "Giáo Dục TC", "Điểm TB"
            }
        ));
        tbhienthi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhienthiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbhienthi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(bntfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(bntnext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(bntprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(bntlast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bntNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bntNew)
                        .addGap(18, 18, 18)
                        .addComponent(bntSave)
                        .addGap(18, 18, 18)
                        .addComponent(bntdelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntnext, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntlast, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntsearchActionPerformed

        rs = find(txtTiemKiemMaSV.getText());
         
         try{
             if(rs.next()){
                 txtHoTenSV.setText(rs.getString("HoTen"));
                 txtMaSV.setText(rs.getString("MaSV"));
             }else{
                 JOptionPane.showMessageDialog(this, "Không tìm thấy");
             }
         }catch(Exception e){
             JOptionPane.showMessageDialog(this, "Lỗi Data");
         }
    }//GEN-LAST:event_bntsearchActionPerformed

    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSaveActionPerformed
        // TODO add your handling code here:
         if(CheckInput()){
            try{
               con = DatabaseAcc.getDatabaseAcc();
               //lấy dữ liệu bảng từ dattabase
               pst = con.prepareStatement("INSERT INTO grade(MaSV,HoTenSV,TiengAnh,TinHoc,GDTC,DiemTB)"+
                       "values(?,?,?,?,?,?)");
               pst.setString(1, txtMaSV.getText());
               pst.setString(2, txtHoTenSV.getText());
               pst.setDouble(3, Double.parseDouble(txtTiengAnh.getText()));
               pst.setDouble(4, Double.parseDouble(txtTinHoc.getText()));
               pst.setDouble(5, Double.parseDouble(txtGiaoDucTC.getText()));
               pst.setDouble(6, Double.parseDouble(txtDiemTB.getText()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                showTable();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this, "Thêm không thành công");
        }
    }//GEN-LAST:event_bntSaveActionPerformed

    private void txtDiemTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiemTBMouseClicked
        // TODO add your handling code here:
        double ta,th,gdtc,diemtb;
        ta =Double.parseDouble(txtTiengAnh.getText());
         th =Double.parseDouble(txtTinHoc.getText());
          gdtc =Double.parseDouble(txtGiaoDucTC.getText());
          diemtb = (ta + th + gdtc)/3;
           txtDiemTB.setText(""+diemtb);
    }//GEN-LAST:event_txtDiemTBMouseClicked

    private void bntdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdeleteActionPerformed
        // TODO add your handling code here:
        if(!txtMaSV.getText().equals("")){
            try {
            // TODO add your handling code here:
            con = DatabaseAcc.getDatabaseAcc();
            pst = con.prepareStatement("DELETE FROM grade WHERE MaSV = ?");
            String maSV = txtMaSV.getText();
            pst.setString(1, maSV);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            showTable();
        } catch (SQLException ex) {
            Logger.getLogger(QLDiem.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Xóa không thành công");
        }
        }else{
            JOptionPane.showMessageDialog(this, "Lỗi data");
        }
    }//GEN-LAST:event_bntdeleteActionPerformed

    private void tbhienthiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhienthiMouseClicked
        // TODO add your handling code here:
        int index = tbhienthi.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_tbhienthiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(CheckInput()){
            String UpString = null;
            pst = null;
              con = DatabaseAcc.getDatabaseAcc();
                  try{
                   UpString = "UPDATE grade SET MaSV = ?,HoTenSV = ?,TiengAnh = ?,TinHoc = ?,GDTC = ?,DiemTB = ?"
                            + " WHERE MaSV = ?";
                    pst =con.prepareStatement(UpString);
                    pst.setString(1, txtMaSV.getText());
               pst.setString(2, txtHoTenSV.getText());
              pst.setDouble(3, Double.parseDouble(txtTiengAnh.getText()));
               pst.setDouble(4, Double.parseDouble(txtTinHoc.getText()));
               pst.setDouble(5, Double.parseDouble(txtGiaoDucTC.getText()));
               pst.setDouble(6, Double.parseDouble(txtDiemTB.getText()));
                 pst.setString(7, txtMaSV.getText());
               pst.executeUpdate();
               JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                this.Clead();
                showTable();
              }catch(Exception e){
                  JOptionPane.showMessageDialog(null, e.getMessage());
              }
             
        }else{
            JOptionPane.showMessageDialog(this, "Cập nhật không thành công");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bntNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNewActionPerformed
        // TODO add your handling code here:
        this.Clead();
    }//GEN-LAST:event_bntNewActionPerformed

    private void bntfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntfirstActionPerformed
        // TODO add your handling code here:
        pos = 0;
        ShowItem(pos);
    }//GEN-LAST:event_bntfirstActionPerformed

    private void bntlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntlastActionPerformed
        // TODO add your handling code here:
        pos = getGradeList().size()-1;
        ShowItem(pos);
    }//GEN-LAST:event_bntlastActionPerformed

    private void bntnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntnextActionPerformed
        // TODO add your handling code here:
        pos ++;
        if(pos >=getGradeList().size()){
            pos = getGradeList().size()-1;
        }
        ShowItem(pos);
    }//GEN-LAST:event_bntnextActionPerformed

    private void bntpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntpreviousActionPerformed
        // TODO add your handling code here:
        pos --;
        if(pos<0){
            pos =0;
        }
        ShowItem(pos);
    }//GEN-LAST:event_bntpreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntNew;
    private javax.swing.JButton bntSave;
    private javax.swing.JButton bntdelete;
    private javax.swing.JButton bntfirst;
    private javax.swing.JButton bntlast;
    private javax.swing.JButton bntnext;
    private javax.swing.JButton bntprevious;
    private javax.swing.JButton bntsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbhienthi;
    private javax.swing.JTextField txtDiemTB;
    private javax.swing.JTextField txtGiaoDucTC;
    private javax.swing.JTextField txtHoTenSV;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTiemKiemMaSV;
    private javax.swing.JTextField txtTiengAnh;
    private javax.swing.JTextField txtTinHoc;
    // End of variables declaration//GEN-END:variables
}
